services:
  localstack:
    image: localstack/localstack:3.2.0
    container_name: localstack
    ports:
      - '4566-4583:4566-4583'
      - '4510-4559:4510-4559'
    volumes:
      - ./scripts:/scripts
