version: '3.3'
services:
  localstack:
    container_name: localstack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4566-4583:4566-4583'
    command: docker exec -it localstack sh -c "/usr/local/bin/create_bucket.sh" # Won't run as docker won't exist inside the container
