services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: testpwd
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - 5432:5432

  airflow:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_FOLDER: /data/dags
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      AIRFLOW__LOGGING__LOGGING_LEVEL: ${LOGGER_LEVELS_ROOT:-INFO}
      AIRFLOW__WEBSERVER__ACCESS_LOGFILE: '/dev/null'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      AIRFLOW__SECRETS__BACKEND: airflow.secrets.local_filesystem.LocalFilesystemBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"variables_file_path": "/data/variables.yml", "connections_file_path": "/data/connections.yml"}'
    ports:
      - '8080:8080'
      - '8793:8793'
      - '8794:8794'
    volumes:
      - ./airflow:/data
      - ./out:/out
    command: 'standalone'