version: '3.7'
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    container_name: kib01-test
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:7.17.9
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Without this, too many notifications in kibana with every page refresh
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: es01-test
    networks:
      - elastic
      
networks:
  elastic: