version: '3.7'

services:
  grafana:
    image: grafana/grafana-oss:9.5.1
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH__FILE=/run/secrets/default_home_dashboard_path
    ports:
      - 3000:3000
    container_name: grafana
    volumes:
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    secrets:
      - admin_user
      - admin_password
      - default_home_dashboard_path

secrets:
  admin_password:
    file: ./admin_password.txt
  admin_user:
    file: ./admin_user.txt
  default_home_dashboard_path:
    file: ./default_home_dashboard_path.txt