version: '3.7'

services:
  htpasswd:
    image: httpd:2
    command: 'htpasswd -Bb /auth/htpasswd testuser testpwd'
    volumes:
      - ./auth:/auth

  registry:
    image: registry:2
    depends_on:
      - htpasswd
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./auth:/auth