version: '3.7'
services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
     - 8081:8081
     - 10250-10255:10250-10255
    mem_reservation: 3G
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 3
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: 'true'
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: $IP_ADDR
      # Default cosmos emulator key
      AZURE_COSMOS_EMULATOR_KEY: 'C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='